name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
   
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        
      - 
        name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker_sshd:$(date +%s)       
      -
        name: Login to Docker Hub
        uses: ./
        with:
          image: risapav/docker_sshd
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

